SUPABASE_URL = "https://fyjegrocqkzhcyygkbrh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5amVncm9jcWt6aGN5eWdrYnJoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjA1NjM2MSwiZXhwIjoyMDY3NjMyMzYxfQ.pwj6feIebSS4F7P6-gdFz4qYpv9ZHJ7eeXYrn76KjMI"
